import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "next-themes"
import { HotNavigationProvider } from "hot-nav";
import CustomCursor from "@/components/custom-cursor";
import { Background } from "@/components/background";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Nick's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en suppressHydrationWarning">
      <body className="overflow-x-hidden">
        <div className={`${geistSans.variable} ${geistMono.variable } antialiased mx-auto min-h-screen max-w-screen-xl py-12 font-sans md:px-12 md:py-20 lg:py-0`}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Background />
          <HotNavigationProvider addCustomStyles={false} defaultHotKeysOn={true} >
            <CustomCursor>
              {children}
            </CustomCursor>
          </HotNavigationProvider>
        </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
